// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_ECommerce.Data;

namespace dotnet_ECommerce.Migrations.StoreDb
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("dotnet_ECommerce.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "A combination of multiple small cactuses",
                            Image = "/../../wwwroot/images/cactus_atlantic.jpg",
                            Name = "Atlantic",
                            Price = 12m,
                            Sku = "CAC001"
                        },
                        new
                        {
                            ID = 2,
                            Description = "A hot pink little cactus to bright up your room",
                            Image = "/../../wwwroot/images/cactus_rosette.jpg",
                            Name = "Rosette",
                            Price = 9m,
                            Sku = "CAC002"
                        },
                        new
                        {
                            ID = 3,
                            Description = "This cactus with elegant-looking glass is perfect for your desk",
                            Image = "/../../wwwroot/images/cactus_pastel.jpg",
                            Name = "Pastel",
                            Price = 7m,
                            Sku = "CAC003"
                        },
                        new
                        {
                            ID = 4,
                            Description = "This cute little coral will definitely lighten up your mood",
                            Image = "/../../wwwroot/images/cactus_coral.jpg",
                            Name = "Coral",
                            Price = 10m,
                            Sku = "CAC004"
                        },
                        new
                        {
                            ID = 5,
                            Description = "The unique looking little parakeet is one of the tiny plants that you must have",
                            Image = "/../../wwwroot/images/cactus_parakeet.jpg",
                            Name = "Parakeet",
                            Price = 18m,
                            Sku = "CAC005"
                        },
                        new
                        {
                            ID = 6,
                            Description = "This spiky and layered looking cactus is defenitely a rare found",
                            Image = "/../../wwwroot/images/cactus_crimson.jpg",
                            Name = "Crimson",
                            Price = 17m,
                            Sku = "CAC006"
                        },
                        new
                        {
                            ID = 7,
                            Description = "A blue orchid is one of the best indoor plants that you can have",
                            Image = "/../../wwwroot/images/flower_arctic.jpg",
                            Name = "Arctic",
                            Price = 24m,
                            Sku = "FLW001"
                        },
                        new
                        {
                            ID = 8,
                            Description = "This ornamental plant comes with violet flowers and kokedama that adds more style to your plant",
                            Image = "/../../wwwroot/images/flower_kokedama.jpg",
                            Name = "Violet Kokedama",
                            Price = 29m,
                            Sku = "FLW002"
                        },
                        new
                        {
                            ID = 9,
                            Description = "Bamboo is easy to take care of and it grows fast",
                            Image = "/../../wwwroot/images/plant_bamboo.jpg",
                            Name = "Bamboo",
                            Price = 26m,
                            Sku = "PLN001"
                        },
                        new
                        {
                            ID = 10,
                            Description = "This plant can live in water and it makes a great indoor plant",
                            Image = "/../../wwwroot/images/plant_hyacinth.jpg",
                            Name = "Hyacinth",
                            Price = 22m,
                            Sku = "PLN002"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
